email: 

cluster:
  endpoint: "https://localhost:63103"

subdomain: "notsoducking-rasa-chatbot"
license: FT7YCAYBAEDUY2LDMVXHGZIB76BAAAIDAECEIYLUMEAQUAABAFJAD74EAAAQCUYB76CAAAAABL7YGBIBAL7YMAAAAD7ACEH7QIA77JD3EJ3GK4TTNFXW4IR2GIWCEZLNMFUWYIR2EJXGS43IMFXHILRQG43GEY3UGAZDGQDUMNUW6ZJOMVSHKLTOOARCYITDN5WXAYLOPERDUISUNBQXAYLUNBQWY2JAIVXGO2LOMVSXE2LOM4QEGYLNOB2XGIRMEJZWKYLUOMRDUMZQFQRHI2LFOIRDUITTMNQWYZJCFQRHI4TJMFWCEOTUOJ2WKLBCMVXGIIR2EIZDAMRUFUYDGLJSG5KDCNJ2GI4TUMBVLIRH2AJRALAVXIUIMTTR2XGMJI3KXBIBXRK3IHSY4TNMYN2CP33BH6NOABJ5ATWJTSZPKG7AWGMT4NWR4X4XLPABGEBFAO2ZPMVG2QNKXXXODX3SQDMUK2636OOQCPCWEH2HXQJTJHYY5FZ2PD6HTT4XU4O7ZWKIR5KBJ5ULAA======

auth:
  google:
    enabled: true
    clientId: 
    clientSecret: 

cloud:
  provider:
    aws:
      enabled: true
      bucket:
      region:
      iam:
        accessKeyID: